-- ══════════════════════════════════════════════════
-- GRAVI — Seed Content: Prompts + Debate Topics
-- ══════════════════════════════════════════════════

-- ── Prompts ───────────────────────────────────────
insert into public.prompts (title, description, category, duration_minutes, difficulty, language, is_featured) values
('The Art of Executive Presence', 'Deliver a compelling 2-minute introduction of yourself as a senior leader. Focus on authority, clarity, and gravitas. Share your vision and what drives your leadership philosophy.', 'Leadership', 2, 'intermediate', 'en', true),
('Pitch to a Skeptical Investor', 'You have 5 minutes to pitch your startup to a VC who has seen 1000 pitches and is skeptical. Make them believe in both the market and you. Address objections before they arise.', 'Pitch', 5, 'advanced', 'en', true),
('The Future of AI in Your Industry', 'Discuss the transformative impact of artificial intelligence on your industry over the next decade. Include opportunities, threats, and your organisation''s readiness.', 'Innovation', 5, 'intermediate', 'en', true),
('Delivering Difficult Feedback', 'You need to give constructive feedback to a high-performing team member whose behaviour is affecting the team. Be direct, specific, and compassionate.', 'Leadership', 3, 'intermediate', 'en', false),
('Tell Me About Yourself (Interview)', 'Classic interview question — but done at the executive level. In 2 minutes, tell your professional story in a way that''s compelling, memorable, and strategically positioned.', 'Interview', 2, 'beginner', 'en', true),
('Crisis Communication: The First 5 Minutes', 'You are addressing stakeholders in the first 5 minutes of a product crisis. Acknowledge the issue, take responsibility, and outline immediate steps — without overpromising.', 'Business', 5, 'advanced', 'en', false),
('Why I Changed My Mind', 'Describe a significant belief or strategy you held that you changed based on new evidence. What drove the change? What did you learn? Why does intellectual humility matter in leadership?', 'Storytelling', 3, 'intermediate', 'en', false),
('The Business Case for Diversity', 'Make a compelling, data-driven argument for why diversity in leadership teams directly improves business outcomes. Speak to a board of directors.', 'Ethics', 5, 'intermediate', 'en', false),
('Negotiating a Major Deal', 'Walk through your approach to negotiating a high-stakes business deal. Cover preparation, principles, tactics, and how you handle impasses.', 'Negotiation', 5, 'advanced', 'en', false),
('Inspiring Your Team Through Uncertainty', 'Your team is anxious about a major company restructure. Deliver a 3-minute address that is honest, grounding, and motivating — without false promises.', 'Leadership', 3, 'intermediate', 'en', true),
('The 60-Second Pitch', 'You are in an elevator with the CEO of your dream client. You have 60 seconds to explain what you do and why they should care. Every word counts.', 'Pitch', 1, 'beginner', 'en', false),
('What Does Success Look Like?', 'Define your personal and professional definition of success. Challenge conventional metrics. This is a reflective prompt about values, purpose, and long-term vision.', 'Storytelling', 3, 'beginner', 'en', false),
('Presenting Complexity Simply', 'Take a genuinely complex concept from your field and explain it clearly and compellingly to a non-expert audience in 3 minutes. No jargon. Pure clarity.', 'Business', 3, 'intermediate', 'en', false),
('Your Biggest Professional Failure', 'Describe your biggest professional failure. Be specific, honest, and show what you learned and how it shaped your approach. This is a high-stakes interview question.', 'Interview', 3, 'intermediate', 'en', false),
('The TED-Style Opening', 'Craft and deliver the first 2 minutes of a TED-style talk. Hook the audience with a counterintuitive idea, a personal story, or a startling fact. Leave them desperate to hear more.', 'Storytelling', 2, 'advanced', 'en', true);

-- ── Debate Topics ─────────────────────────────────
insert into public.debate_topics (title, description, category, difficulty, language, is_featured) values
('AI will eliminate more jobs than it creates in the next decade', 'As artificial intelligence accelerates, the debate over its net effect on employment intensifies. Is technological disruption fundamentally different this time, or will new industries absorb displaced workers?', 'Technology', 'intermediate', 'en', true),
('Remote work is net negative for organisational culture', 'The shift to remote and hybrid work changed how we collaborate, build trust, and maintain culture. Does physical presence matter for high-performance teams, or is this a relic of old management thinking?', 'Business', 'beginner', 'en', true),
('Shareholder value maximisation is ethically indefensible in 2025', 'Milton Friedman''s doctrine dominated business for 50 years. But in an era of climate crisis, inequality, and stakeholder capitalism — is it time to retire it permanently?', 'Ethics', 'advanced', 'en', false),
('Venture capital does more harm than good to the startup ecosystem', 'VC funding has created trillion-dollar companies and thousands of jobs. But it has also fuelled unsustainable burn rates, a winner-takes-all mentality, and a homogenisation of founder profiles. Is it net positive?', 'Startups', 'advanced', 'en', false),
('Governments should regulate social media algorithms', 'Algorithmic amplification has been linked to polarisation, misinformation, and mental health crises. But regulation risks censorship and stifles innovation. Where is the line?', 'Politics', 'intermediate', 'en', true),
('Leaders are born, not made', 'Is leadership primarily innate — a function of personality and temperament — or is it a learnable set of skills and behaviours? This age-old question has real implications for how we hire, train, and develop leaders.', 'Leadership', 'beginner', 'en', true),
('Universal Basic Income should be implemented globally', 'As automation displaces workers and inequality grows, UBI is gaining traction as a policy solution. Is it an economic lifeline or an unaffordable utopian fantasy?', 'Economics', 'intermediate', 'en', false),
('The four-day work week should become the global standard', 'Trials in multiple countries have shown productivity maintained or improved with a four-day week. Is this the future of work, or does it ignore the realities of competitive global markets?', 'Society', 'beginner', 'en', false),
('Cancel culture has made public discourse worse', 'Online accountability campaigns have toppled powerful figures and amplified marginalised voices. But have they also created a culture of fear, reduced nuance, and stifled legitimate debate?', 'Society', 'intermediate', 'en', false),
('Meritocracy is a myth that perpetuates inequality', 'Belief in meritocracy — that success reflects talent and effort — underpins most capitalist societies. But critics argue it ignores structural advantages and creates a moral cover for inequality.', 'Ethics', 'advanced', 'en', false),
('Cities should ban private car ownership in their centres', 'Urban congestion, pollution, and safety data increasingly argue for car-free cities. But mobility, economic freedom, and infrastructure realities complicate the case.', 'Society', 'intermediate', 'en', false),
('Open source AI development poses an existential risk', 'Should powerful AI models be developed openly, enabling innovation and democratisation? Or does releasing them without safeguards accelerate catastrophic misuse?', 'Technology', 'advanced', 'en', true);
